### Assignment 3

##### Ujjwal Chowdhury

In [1]:
# Importing Libraries....................
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt

In [34]:
class Lasso_Regression():

    def __init__(self, learning_rate, no_of_iterations, lambda_parameter):

        self.learning_rate = learning_rate
        self.no_of_iterations = no_of_iterations
        self.lambda_parameter = lambda_parameter
    
################
    def fit(self, X, Y):
        
        self.m, self.n = X.shape  # m = number of Data points , n = number of input features

        self.w = np.zeros(self.n)
        self.b = 0
        self.X = X
        self.Y = Y

        for i in range(self.no_of_iterations):
            self.upadte_weights()

   
# For updating the weight & bias value

    def upadte_weights(self):
        Y_prediction = self.predict(self.X)
        dw = np.zeros(self.n) # dw = gradient for weight
        
        for i in range(self.n):
            if self.w[i]>0:
                dw[i] = (-(2*(self.X[:,i]).dot(self.Y - Y_prediction)) + self.lambda_parameter) / self.m 
            else :
                dw[i] = (-(2*(self.X[:,i]).dot(self.Y - Y_prediction)) - self.lambda_parameter) / self.m

    
        db = - 2 * np.sum(self.Y - Y_prediction) / self.m # gradient for bias

        self.w = self.w - self.learning_rate*dw
        self.b = self.b - self.learning_rate*db

 # function for prediction   
    def predict(self,X):
        return X.dot(self.w) + self.b




In [35]:
#Testing
data = pd.read_csv("annotated_points_np_60.csv")
data.head()

x          y  labels
0  1.330645  19.415584     1.0
1  1.633065  18.766234     1.0
2  2.358871  17.792208     1.0
3  3.387097  16.818182     1.0
4  4.475806  16.087662     1.0

In [36]:
data.shape

(60, 3)

In [50]:
X = np.array(data.loc[:, ["x","y"]])
y = data.iloc[:,2].values

In [51]:
y

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
       1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [52]:
y.ndim

1

In [53]:
print(X.shape,y.shape)

(60, 2) (60,)


In [54]:
# split the dataset into train and test sets
from sklearn.model_selection import train_test_split
X_train, X_test, y_train,y_test = train_test_split(X, y, test_size=0.1, shuffle=True)

In [126]:
lasso_model = Lasso_Regression(learning_rate = 0.001, no_of_iterations=9000,lambda_parameter=0.1)

In [127]:
lasso_model.fit(X_train, y_train)

In [128]:
test_data_prediction = lasso_model.predict(X_test)

In [129]:
print(test_data_prediction)

[1.07103628 0.86652196 1.02130283 0.96785322 1.14847703 1.16733148]


In [130]:
y_test

array([1., 1., 1., 1., 1., 1.])

In [131]:
from sklearn import metrics

# R squared error
score_1 = metrics.r2_score(y_test, test_data_prediction)

# Mean Absolute Error
score_2 = metrics.mean_absolute_error(y_test, test_data_prediction)

print("R squared error : ", score_1) #standardized version of MSE
print('Mean Absolute Error : ', score_2)

R squared error :  0.0
Mean Absolute Error :  0.09562873987784955
