In [1]:
import numpy as np

In [1]:
#python lists are heterogeneous
L3 = [True, "2", 3.0, 4]
[type(item) for item in L3]

[bool, str, float, int]

In [2]:
#python arrays little better - provides more efficient storage but not efficient operations on them
import array
L = list(range(10))
A = array.array('i', L); A


array('i', [0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
#numpy arrays provide efficient array based storage as well as efficient operations - ufuncs, etc.
import numpy as np
my_arr = np.arange(100)
my_list = list(range(100))
print(my_arr)
print(my_list)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53, 54, 55, 56, 57, 58, 59, 60, 61, 62, 63, 64, 65, 66, 67, 68, 69, 70, 71, 72, 73, 74, 75, 76, 77, 78, 79, 80, 81, 82, 83, 84, 85, 86, 87, 88, 89, 90, 91, 92, 93, 94, 95, 96, 97, 98, 99]


In [5]:
#BAD---->>>>>using list.append
import time
start = time.time()
for _ in range(10):
    my_list2=[]
    for e in my_list:
        my_list2.append(e*2)
elapsed_time = (time.time() - start)
#my_list2
elapsed_time

0.0

In [6]:
#BETTER----->>>>>>using list comprehension
import time
start = time.time()
for _ in range(10): my_list2 = [x * 2 for x in my_list]
elapsed_time = (time.time() - start)
#my_list2
elapsed_time

0.0

In [10]:
#BEST--------->>>>>>>>>>>>>>using numpy array
import time
start = time.time()
for _ in range(10): my_arr2 = my_arr * 2
elapsed_time = (time.time() - start)
#my_arr2
elapsed_time

0.0

In [12]:
arr = np.array([1, 4, 2, 5, 3]); arr

array([1, 4, 2, 5, 3])

In [13]:
#list to ndarray
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1); arr1

array([6. , 7.5, 8. , 0. , 1. ])

In [15]:
data1 = [6, 7.5, 8, 0, 1]
arr1 = np.array(data1,dtype=np.float64) 
print(arr1.itemsize)
arr1

8


array([6. , 7.5, 8. , 0. , 1. ])

In [57]:
data11 = [6, 7.5, 8, 0, 1]
arr11 = np.array(data11,dtype='float16')
print(arr11)
arr11.itemsize #  bit = 1 byte so 16 bit = 16/8 = 2 byte ** Hence itemsize = 2

[6.  7.5 8.  0.  1. ]


2

In [21]:
#nested list to multidimensional ndarray
data2 = [[1, 2, 3, 4], [5, 6, 7, 8]]
arr2 = np.array(data2); arr2

array([[1, 2, 3, 4],
       [5, 6, 7, 8]])

In [22]:
data = np.random.randn(2, 3)
print(data)
print(data.shape    ,data.ndim   ,data.dtype   ,data.itemsize   ,data.size   ,data.nbytes)

[[ 0.3128756   0.30628172 -0.59174622]
 [-0.52274975  0.22512711 -0.30372888]]
(2, 3) 2 float64 8 6 48


In [24]:
np.arange(10)


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [25]:
np.arange(2, 10, dtype=float)

array([2., 3., 4., 5., 6., 7., 8., 9.])

In [26]:
#overflow and trucation errors
print(np.power(100, 8, dtype=np.int64))
print(np.power(100, 8, dtype=np.int32))
print(np.power(100, 100, dtype=np.int64))
print(np.power(100, 100, dtype=np.float64))

10000000000000000
1874919424
0
1e+200


In [27]:
arr11 = np.array([1.3,2.5], dtype=np.int16)
arr11

array([1, 2], dtype=int16)

In [28]:
x = np.arange(10,1,-1); print(x)
print(x[[3, 3, 1, 8]])


[10  9  8  7  6  5  4  3  2]
[7 7 9 2]


In [42]:
x[[3,3,-8,8]] # - 8 means counting from right side

array([7, 7, 9, 2])

In [44]:
#use of standard numpy functions to create arrays
print(np.zeros(10))
np.zeros((3, 6))


[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [51]:
#uninitialized garbage values
np.empty(1)


array([1.90979621e-313])

In [53]:
print(np.arange(15))
print(np.arange(3,10,2))
print(np.arange(3,10,2,dtype='float'))
print(np.arange(3,10,2,dtype=np.float64))


[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
[3 5 7 9]
[3. 5. 7. 9.]
[3. 5. 7. 9.]


In [58]:
arr14 = np.eye(3); print(arr14)
arr22 = np.linspace(3,100,12); print(arr22)
np.eye(3)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[  3.          11.81818182  20.63636364  29.45454545  38.27272727
  47.09090909  55.90909091  64.72727273  73.54545455  82.36363636
  91.18181818 100.        ]


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [64]:
#indexing of arrays - single index, slicing, boolean indexing, fancy indexing, multi-dimensional subarrays
arr12 = np.array([[2,3,4],[3,5,3]]) 
print("arr12 = np.array([[2,3,4],[3,5,3]]) ")
print(arr12)
#for multidimensional, dimensions are separated by commas
print("(arr12[1,1])")
print(arr12[1,1])
print("(arr12[1,1:])")
print(arr12[1,1:])
print("(arr12[:1, :2])")
print(arr12[:1, :2])
print("(arr12[:,:2])")
print(arr12[:,:2])
print("(arr12[:1,:])")
print(arr12[:1,:])    #alternatively arr12[:1]
data1 = [6, 7.5, 8, 0, 1]; arr1 = np.array(data1)
print("(arr1[2:-1])")
print(arr1[2:-1])
arr16 = arr1[2:4]; print(arr16)


arr12 = np.array([[2,3,4],[3,5,3]]) 
[[2 3 4]
 [3 5 3]]
(arr12[1,1])
5
(arr12[1,1:])
[5 3]
(arr12[:1, :2])
[[2 3]]
(arr12[:,:2])
[[2 3]
 [3 5]]
(arr12[:1,:])
[[2 3 4]]
(arr1[2:-1])
[8. 0.]
[8. 0.]


In [66]:
arr112 = np.array([[2,3,4],[9,8,7]]) 
arr112


array([[2, 3, 4],
       [9, 8, 7]])

In [68]:

#for multidimensional, dimensions are separated by commas
print(arr112[1,1])


8


In [69]:

print(arr112[1,1:])


[8 7]


In [97]:

print(arr112[:1,:1])


[[2]]


In [ ]:
print("(arr12[:,:2])")
print(arr12[:,:2])
print("(arr12[:1,:])")
print(arr12[:1,:]) 

In [112]:
data111 = [6, 7.5, 8, 0, 1]; arr111 = np.array(data1)
print("(arr111[2:-1])")
print(arr111[2:-1])
arr1116 = arr111[2:4]; print(arr1116)

(arr111[2:-1])
[8. 0.]
[8. 0.]


In [ ]:
###################################################3

In [115]:
#array indexing is a no copy operation
arr16 = arr1[2:4]; print(arr16)
arr16[0]=100; arr16


[100.   0.]


array([100.,   0.])

In [119]:
#getting a copy
arr16 = arr1[2:4].copy(); arr16


array([1000.,    0.])

In [121]:
arr16[0]=1000; print(arr16)
arr1

[1000.    0.]


array([   6. ,    7.5, 1000. ,    0. ,    1. ])

In [122]:
#array reshaping
#row major arrangement (C-style)
arr22 = np.linspace(3,100,12); print(arr22)
arr22_reshaped = arr22.reshape(6,2); arr22_reshaped

[  3.          11.81818182  20.63636364  29.45454545  38.27272727
  47.09090909  55.90909091  64.72727273  73.54545455  82.36363636
  91.18181818 100.        ]


array([[  3.        ,  11.81818182],
       [ 20.63636364,  29.45454545],
       [ 38.27272727,  47.09090909],
       [ 55.90909091,  64.72727273],
       [ 73.54545455,  82.36363636],
       [ 91.18181818, 100.        ]])

In [123]:
#column major arrangement (Fortran style)
arr22_reshaped = arr22.reshape(6,2,order='F'); arr22_reshaped

array([[  3.        ,  55.90909091],
       [ 11.81818182,  64.72727273],
       [ 20.63636364,  73.54545455],
       [ 29.45454545,  82.36363636],
       [ 38.27272727,  91.18181818],
       [ 47.09090909, 100.        ]])

In [134]:
arr22_reshaped[1:6:2,:1]

array([[11.81818182],
       [29.45454545],
       [47.09090909]])

In [137]:
x = np.array([1, 2, 3])
y = x.reshape((1, 3));y


array([[1, 2, 3]])

In [138]:
print(y.shape,x.shape)


(1, 3) (3,)


In [139]:
y = x[np.newaxis, :];print(y)
y.shape


[[1 2 3]]


(1, 3)

In [140]:
y = x[:, np.newaxis];print(y)
y.shape

[[1]
 [2]
 [3]]


(3, 1)

In [141]:
#array concatenation & splitting
x = np.array([1, 2, 3])
y = np.array([3, 2, 1])
np.concatenate([x, y],axis=0)


array([1, 2, 3, 3, 2, 1])

In [142]:
np.concatenate([x[:,np.newaxis],y[:,np.newaxis]])


array([[1],
       [2],
       [3],
       [3],
       [2],
       [1]])

In [143]:
np.concatenate([x[:,np.newaxis],y[:,np.newaxis]],axis=1)


array([[1, 3],
       [2, 2],
       [3, 1]])

In [145]:
np.hstack([x,y])


array([1, 2, 3, 3, 2, 1])

In [146]:
np.vstack([x,y])

array([[1, 2, 3],
       [3, 2, 1]])

In [4]:
x=[1,2,3,5,99,3,2,1]
x1, x2, x3 = np.split(x, [3,4])
print(x1, x2, x3) #also explore np.hsplit, np.vsplit

[1 2 3] [5] [99  3  2  1]


In [148]:
np.split?

In [161]:
###################################

In [11]:
x = np.arange(10.0) ; print(x)
np.split(x, [3, 4, 6, 10])

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


[array([0., 1., 2.]),
 array([3.]),
 array([4., 5.]),
 array([6., 7., 8., 9.]),
 array([], dtype=float64)]

In [13]:
#boolean masks and boolean indexing
arr14 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr14

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [14]:
arr14%2==0


array([[False,  True, False],
       [ True, False,  True],
       [False,  True, False]])

In [20]:
arr14[arr14%2==0].reshape(4,1)


array([[2],
       [4],
       [6],
       [8]])

In [21]:
arr15 = np.array([True,False,True]); arr15


array([ True, False,  True])

In [22]:
arr14[arr15]


array([[1, 2, 3],
       [7, 8, 9]])

In [23]:
arr16 = np.array([[True,False,True],[True, True,False],[False,False,True]])


In [24]:
arr14[arr16]


array([1, 3, 4, 5, 9])

In [25]:
arr14[~arr14%2==0]


array([1, 3, 5, 7, 9])

In [26]:
arr14[(arr14%2==0) | (arr14%9==0)]

array([2, 4, 6, 8, 9])

In [28]:
#fancy indexing (index arrays using lists)
#fancy indexing results into COPYING
x = np.arange(10,1,-1); print(x)
print(x[[3, 3, 1, 8]])
print(x[[3,3,-3,8]])

arr = np.empty((8, 4))
for i in range(8):
    arr[i] = i
arr

[10  9  8  7  6  5  4  3  2]
[7 7 9 2]
[7 7 4 2]


array([[0., 0., 0., 0.],
       [1., 1., 1., 1.],
       [2., 2., 2., 2.],
       [3., 3., 3., 3.],
       [4., 4., 4., 4.],
       [5., 5., 5., 5.],
       [6., 6., 6., 6.],
       [7., 7., 7., 7.]])

In [29]:
#pass the array index as a list
arr[[4, 3, 0, 6]]




array([[4., 4., 4., 4.],
       [3., 3., 3., 3.],
       [0., 0., 0., 0.],
       [6., 6., 6., 6.]])

In [31]:
arr = np.arange(32).reshape((8, 4))
arr


array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23],
       [24, 25, 26, 27],
       [28, 29, 30, 31]])

In [32]:

#here the 1st, 5th, 7th and 2nd rows' 0th, 3rd, 1st and 2nd elements are selected respectively. 
#The result is an one-dimensional array
arr[[1, 5, 7, 2], [0, 3, 1, 2]]


array([ 4, 23, 29, 10])

In [33]:
arr[[1, 5, 7, 2], [0, 3, 1, 2]]=0
arr



array([[ 0,  1,  2,  3],
       [ 0,  5,  6,  7],
       [ 8,  9,  0, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22,  0],
       [24, 25, 26, 27],
       [28,  0, 30, 31]])

In [34]:
#important note the differences and similarities
arr[1,2]


6

In [35]:
arr[(1,2)] #same as previous


6

In [36]:
arr[[1,2]] #not same as previous but example of fancy indexing

array([[ 0,  5,  6,  7],
       [ 8,  9,  0, 11]])

In [38]:
#UFUNCS
arr12 = np.array([[2,3,4],[3,5,3]]); arr12


array([[2, 3, 4],
       [3, 5, 3]])

In [39]:
arr12 + arr12 #  (Like matrix addition)


array([[ 4,  6,  8],
       [ 6, 10,  6]])

In [40]:
arr12 * arr12 # Multilpuig each elements (Unlike Matrix multiplication)


array([[ 4,  9, 16],
       [ 9, 25,  9]])

In [41]:
arr12 * 3 # Multiplin each element with 3


array([[ 6,  9, 12],
       [ 9, 15,  9]])

In [42]:
arr12 ** 2   # powerng each element ^2


array([[ 4,  9, 16],
       [ 9, 25,  9]], dtype=int32)

In [43]:
arr14 = np.eye(3); arr14 # Identity matrix


array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [44]:
arr12 > arr12 * 2


array([[False, False, False],
       [False, False, False]])

In [45]:
arr15 = np.array([[1,3,4],[3,4,3]])
arr12<=arr15


array([[False,  True,  True],
       [ True, False,  True]])

In [46]:
arr16 = np.arange(15).reshape(3,5); arr16


array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [47]:
np.sqrt(arr16)


array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ],
       [2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ],
       [3.16227766, 3.31662479, 3.46410162, 3.60555128, 3.74165739]])

In [48]:
x = np.random.randn(8); print(x)
y = np.random.randn(8); print(y)


[ 0.41012284 -0.38561191 -0.63428384  0.89318469  1.03361324  0.23981679
 -0.63407509 -0.27503748]
[ 0.63798111  0.18512536 -1.19610774  0.70228024 -0.14699192 -0.16030458
  1.45368102 -1.0357119 ]


In [49]:
np.maximum(x, y) # Element wise Max


array([ 0.63798111,  0.18512536, -0.63428384,  0.89318469,  1.03361324,
        0.23981679,  1.45368102, -0.27503748])

In [50]:
np.add(x,y)


array([ 1.04810395, -0.20048654, -1.83039158,  1.59546493,  0.88662132,
        0.07951221,  0.81960593, -1.31074938])

In [51]:
arr17 = np.random.randn(7) * 5; arr17


array([-7.87709053,  9.64591214,  3.3436855 , -3.08801816, -2.4513541 ,
        5.34916412,  2.21514069])

In [54]:
remainder, whole_part = np.modf(arr17)
print(remainder)
print(whole_part)
print(np.modf(arr17))

[-0.87709053  0.64591214  0.3436855  -0.08801816 -0.4513541   0.34916412
  0.21514069]
[-7.  9.  3. -3. -2.  5.  2.]
(array([-0.87709053,  0.64591214,  0.3436855 , -0.08801816, -0.4513541 ,
        0.34916412,  0.21514069]), array([-7.,  9.,  3., -3., -2.,  5.,  2.]))


In [55]:
#largest integer smaller than...
np.floor(arr17)


array([-8.,  9.,  3., -4., -3.,  5.,  2.])

In [56]:
arr18 =np.array([np.nan,23,2.3]); arr18


array([ nan, 23. ,  2.3])

In [60]:
print(np.nan)
np.isnan(np.nan)



nan


True

In [61]:
print(np.inf)
np.isnan(np.inf)


inf


False

In [59]:
np.isinf(np.inf)


True

In [62]:
np.isnan(arr18)


array([ True, False, False])

In [63]:
np.array([1])/0


C:\Users\Ujjwa\AppData\Local\Temp/ipykernel_13428/1770903552.py:1: RuntimeWarning: divide by zero encountered in true_divide
  np.array([1])/0


array([inf])

In [65]:
arr16

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [64]:
np.dot(arr16,arr16.T)


array([[ 30,  80, 130],
       [ 80, 255, 430],
       [130, 430, 730]])

In [67]:
np.log([-1, 1, 2])


C:\Users\Ujjwa\AppData\Local\Temp/ipykernel_13428/2871910562.py:1: RuntimeWarning: invalid value encountered in log
  np.log([-1, 1, 2])


array([       nan, 0.        , 0.69314718])

In [68]:
np.mean(arr12) # alternatively arr12.mean()


3.3333333333333335

In [71]:
print(arr12)

[[2 3 4]
 [3 5 3]]


In [72]:
print(arr12.sum())
print(arr12.mean(axis=1)) # Column wise
print(arr12.mean(axis=0)) # Row wise
print()
print(np.mean(arr12,axis=0))
print(arr12.cumsum())


20
[3.         3.66666667]
[2.5 4.  3.5]

[2.5 4.  3.5]
[ 2  5  9 12 17 20]


In [75]:
arr13 = np.array([[0, 1, 2], [3, 4, 5], [6, 7, 8]])
print(arr13)
print()
#for each col
print(arr13.cumsum(axis=0))
#for each row
print(arr13.cumsum(axis=1))



[[0 1 2]
 [3 4 5]
 [6 7 8]]

[[ 0  1  2]
 [ 3  5  7]
 [ 9 12 15]]
[[ 0  1  3]
 [ 3  7 12]
 [ 6 13 21]]


In [76]:
#similarly we have std, var, min, max, argmin, argmax, cumprod
arr14 = np.array([[0, 2, 1], [5, 3, 5], [6, 7, 8]])
print(arr14)
print(arr14.argmin(axis=1))
print(arr14.argmax(axis=1))
print(arr14.max(axis=1))


[[0 2 1]
 [5 3 5]
 [6 7 8]]
[0 1 0]
[1 0 2]
[2 5 8]


In [77]:
#boolean arrays
arr15 = np.random.randn(100)
(arr15 > 0).sum() #count of positive values as True has value 1 and False has 0
(arr15 > 0).any()
(arr15 > 0).all()

#sorting (with copy, w/o copy)
arr14.sort(axis=1)
#in place sorting: NO COPY made
#similar to the sort method of python list (as against sorted() available for any python iterable which makes copy)
arr14
arr15 = np.array([[2,4,3],[3,2,1],[5,2,2]]); arr15
#COPY made
np.sort(arr15,axis=1)
arr15

array([[2, 4, 3],
       [3, 2, 1],
       [5, 2, 2]])