In [1]:
#pandas adopts many coding idioms from NumPy, 
#the biggest difference is that pandas is designed 
#for working with tabular or heterogeneous data

#NumPy is best suited for working with homogeneous numerical array data

In [1]:
import pandas as pd
import numpy as np

In [2]:
from pandas import Series, DataFrame

In [3]:
#A Series is a one-dimensional array-like object containing a sequence of values
#and an associated array of data labels, called its index
#similar to python dict but ordered and also the keys (indexes) and values belong to a single type (i.e. they are typed)
#similar to numpy arrays but explicit indices which need not be integers

In [4]:
s1 =  pd.Series([4, 7, -5, 3]); print(s1)
print("----")
print(s1.axes)
print(s1.index)
print(s1.dtype.kind)
print(s1.dtype.kind in 'iuf')
print(s1.values)
print(s1[2:])
print("===================")
s1 =  pd.Series([4, 7, -5, 3],index=['a','b','e','f']); print(s1)
print(s1.axes)
print(s1.index)
print(s1.dtype.kind)
print(s1.dtype.kind in 'iuf')
print(s1.values)
print("----------")
print(s1[2])  #using integer sequence index
print(s1[2:]) #using integer sequence index
print(s1['e':]) #using given indices
print(s1[['a','e']])  #fancy indexing style

0    4
1    7
2   -5
3    3
dtype: int64
----
[RangeIndex(start=0, stop=4, step=1)]
RangeIndex(start=0, stop=4, step=1)
i
True
[ 4  7 -5  3]
2   -5
3    3
dtype: int64
a    4
b    7
e   -5
f    3
dtype: int64
[Index(['a', 'b', 'e', 'f'], dtype='object')]
Index(['a', 'b', 'e', 'f'], dtype='object')
i
True
[ 4  7 -5  3]
----------
-5
e   -5
f    3
dtype: int64
e   -5
f    3
dtype: int64
a    4
e   -5
dtype: int64


In [6]:
#Series from dictionary
import string
d1 = dict(zip(range(10),string.ascii_lowercase[0:10])); print(d1)
s1 = pd.Series(d1); print(s1); print(type(s1))
print("---------")
s1 = pd.Series(['a','b','c','d'],index=[1,1,2,3]); print(s1); print(type(s1)); print(s1.index)
s1 = pd.Series(['a','b','c','d'],index=[1,'a',2,3]); print(s1); print(type(s1)); print(s1.index)
s1 = pd.Series(np.linspace(1,10,5)); print(s1); print(type(s1)); print(s1.index); print(s1[0])

{0: 'a', 1: 'b', 2: 'c', 3: 'd', 4: 'e', 5: 'f', 6: 'g', 7: 'h', 8: 'i', 9: 'j'}
0    a
1    b
2    c
3    d
4    e
5    f
6    g
7    h
8    i
9    j
dtype: object
<class 'pandas.core.series.Series'>
---------
1    a
1    b
2    c
3    d
dtype: object
<class 'pandas.core.series.Series'>
Int64Index([1, 1, 2, 3], dtype='int64')
1    a
a    b
2    c
3    d
dtype: object
<class 'pandas.core.series.Series'>
Index([1, 'a', 2, 3], dtype='object')
0     1.00
1     3.25
2     5.50
3     7.75
4    10.00
dtype: float64
<class 'pandas.core.series.Series'>
RangeIndex(start=0, stop=5, step=1)
1.0


In [7]:
#A DataFrame represents a rectangular table of data and contains an ordered collection of columns, 
#each of which can be a different value type
#like a dict of Series (REMEMBER dataframe in R was a list of vectors)
#stored as one or more two-dimensional blocks

In [8]:
#Style 1: created in the most basic way as a dict of lists
d5 = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
      'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
print(d5)
df1 = pd.DataFrame(d5); print(df1); 
print(df1.dtypes); 
print("----")
print(df1.index); 
print("----")
print(df1.columns)

{'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 'year': [2000, 2001, 2002, 2001, 2002, 2003], 'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
    state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2
state     object
year       int64
pop      float64
dtype: object
----
RangeIndex(start=0, stop=6, step=1)
----
Index(['state', 'year', 'pop'], dtype='object')


In [9]:
state_list = ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada']
year_list = [2000, 2001, 2002, 2001, 2002, 2003]
population_list = [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]
state_series = pd.Series(dict(zip(["Row"+str(x) for x in range(1,7)],state_list))); print(state_series)
year_series = pd.Series(dict(zip(["Row"+str(x) for x in range(1,7)],year_list))); print(year_series)
population_series = pd.Series(dict(zip(["Row"+str(x) for x in range(1,7)],population_list))); print(population_series)

Row1      Ohio
Row2      Ohio
Row3      Ohio
Row4    Nevada
Row5    Nevada
Row6    Nevada
dtype: object
Row1    2000
Row2    2001
Row3    2002
Row4    2001
Row5    2002
Row6    2003
dtype: int64
Row1    1.5
Row2    1.7
Row3    3.6
Row4    2.4
Row5    2.9
Row6    3.2
dtype: float64


In [10]:
#Style 2: Dataframe as an aligned sequence of Series (dictionary of Series objects)
df1 = pd.DataFrame({'state':state_series,'year':year_series,'population':population_series})
print(df1)
#df1 = pd.DataFrame(d5); print(df1); 
print(df1.dtypes); 
print("----")
print(df1.index); 
print("----")
print(df1.columns)

       state  year  population
Row1    Ohio  2000         1.5
Row2    Ohio  2001         1.7
Row3    Ohio  2002         3.6
Row4  Nevada  2001         2.4
Row5  Nevada  2002         2.9
Row6  Nevada  2003         3.2
state          object
year            int64
population    float64
dtype: object
----
Index(['Row1', 'Row2', 'Row3', 'Row4', 'Row5', 'Row6'], dtype='object')
----
Index(['state', 'year', 'population'], dtype='object')


In [11]:
#Style 3: From list of dicts
list_of_dicts = [{"state":x[0], "year": x[1], "population":x[2]} 
                 for x in list(zip(state_list,year_list,population_list))]; print(list_of_dicts)
print("-----")
df1 = pd.DataFrame(list_of_dicts, index=["Row"+str(x) for x in range(1,7)]); print(df1)

[{'state': 'Ohio', 'year': 2000, 'population': 1.5}, {'state': 'Ohio', 'year': 2001, 'population': 1.7}, {'state': 'Ohio', 'year': 2002, 'population': 3.6}, {'state': 'Nevada', 'year': 2001, 'population': 2.4}, {'state': 'Nevada', 'year': 2002, 'population': 2.9}, {'state': 'Nevada', 'year': 2003, 'population': 3.2}]
-----
       state  year  population
Row1    Ohio  2000         1.5
Row2    Ohio  2001         1.7
Row3    Ohio  2002         3.6
Row4  Nevada  2001         2.4
Row5  Nevada  2002         2.9
Row6  Nevada  2003         3.2


In [12]:
#Style 4: From 2D numpy array
arr1 = np.array(np.arange(1,101)).reshape(10,10); print(arr1)
print("--------")
df1 = pd.DataFrame(arr1,columns=["col"+str(x) for x in range(1,11)], 
                   index=["row"+str(x) for x in range(1,11)]); print(df1)

[[  1   2   3   4   5   6   7   8   9  10]
 [ 11  12  13  14  15  16  17  18  19  20]
 [ 21  22  23  24  25  26  27  28  29  30]
 [ 31  32  33  34  35  36  37  38  39  40]
 [ 41  42  43  44  45  46  47  48  49  50]
 [ 51  52  53  54  55  56  57  58  59  60]
 [ 61  62  63  64  65  66  67  68  69  70]
 [ 71  72  73  74  75  76  77  78  79  80]
 [ 81  82  83  84  85  86  87  88  89  90]
 [ 91  92  93  94  95  96  97  98  99 100]]
--------
       col1  col2  col3  col4  col5  col6  col7  col8  col9  col10
row1      1     2     3     4     5     6     7     8     9     10
row2     11    12    13    14    15    16    17    18    19     20
row3     21    22    23    24    25    26    27    28    29     30
row4     31    32    33    34    35    36    37    38    39     40
row5     41    42    43    44    45    46    47    48    49     50
row6     51    52    53    54    55    56    57    58    59     60
row7     61    62    63    64    65    66    67    68    69     70
row8     71    72    73 

In [13]:
#indexing and selection of Series and Dataframes
#-simple indexing 
#-slicing 
#-boolean masking 
#-index list based (fancy indexing)
#combination of above
print(population_series)

Row1    1.5
Row2    1.7
Row3    3.6
Row4    2.4
Row5    2.9
Row6    3.2
dtype: float64


In [14]:
print(population_series['Row5'])
print("Row3" in population_series)
print(population_series.keys())
print(population_series.items()); print(list(population_series.items()))
population_series["Row7"]=100; print(population_series)
population_series["Row6"]=200; print(population_series)
print(population_series["Row3":"Row5"]) #explicit index
print(population_series[3:6]) #implicit integer index
print(population_series[(population_series >2) & (population_series <4)]) #boolean indexing / masking
print(population_series[["Row1","Row3","Row7"]]) #fancy indexing

2.9
True
Index(['Row1', 'Row2', 'Row3', 'Row4', 'Row5', 'Row6'], dtype='object')
[('Row1', 1.5), ('Row2', 1.7), ('Row3', 3.6), ('Row4', 2.4), ('Row5', 2.9), ('Row6', 3.2)]
Row1      1.5
Row2      1.7
Row3      3.6
Row4      2.4
Row5      2.9
Row6      3.2
Row7    100.0
dtype: float64
Row1      1.5
Row2      1.7
Row3      3.6
Row4      2.4
Row5      2.9
Row6    200.0
Row7    100.0
dtype: float64
Row3    3.6
Row4    2.4
Row5    2.9
dtype: float64
Row4      2.4
Row5      2.9
Row6    200.0
dtype: float64
Row3    3.6
Row4    2.4
Row5    2.9
dtype: float64
Row1      1.5
Row3      3.6
Row7    100.0
dtype: float64


In [15]:
#loc, iloc
data = pd.Series(['a', 'b', 'c'], index=[1, 3, 5]); print(data); print("----")
print(data[1]); print("----") # explicit indexing
print(data[1:3]); print("----") #implicit indexing thro' slicing
print(data.loc[1]); print("----") #refers to explicit index
print(data.loc[1:3]) #refers to explicit index
print(data.iloc[1]); print("----") #'i' for implicit indexing
print(data.iloc[1:3])

1    a
3    b
5    c
dtype: object
----
a
----
3    b
5    c
dtype: object
----
a
----
1    a
3    b
dtype: object
b
----
3    b
5    c
dtype: object


In [16]:
df1 = pd.DataFrame({'state':state_series,'year':year_series,'population':population_series})
print(df1); print("----")
print(df1['state']); print("----") #dict key style
print(df1.state)#attribute style - avoid it to prevent confusion!!!!
print("----")
print(df1.values)
df1.T

       state    year  population
Row1    Ohio  2000.0         1.5
Row2    Ohio  2001.0         1.7
Row3    Ohio  2002.0         3.6
Row4  Nevada  2001.0         2.4
Row5  Nevada  2002.0         2.9
Row6  Nevada  2003.0       200.0
Row7     NaN     NaN       100.0
----
Row1      Ohio
Row2      Ohio
Row3      Ohio
Row4    Nevada
Row5    Nevada
Row6    Nevada
Row7       NaN
Name: state, dtype: object
----
Row1      Ohio
Row2      Ohio
Row3      Ohio
Row4    Nevada
Row5    Nevada
Row6    Nevada
Row7       NaN
Name: state, dtype: object
----
[['Ohio' 2000.0 1.5]
 ['Ohio' 2001.0 1.7]
 ['Ohio' 2002.0 3.6]
 ['Nevada' 2001.0 2.4]
 ['Nevada' 2002.0 2.9]
 ['Nevada' 2003.0 200.0]
 [nan nan 100.0]]


Row1    Row2    Row3    Row4    Row5    Row6   Row7
state         Ohio    Ohio    Ohio  Nevada  Nevada  Nevada    NaN
year        2000.0  2001.0  2002.0  2001.0  2002.0  2003.0    NaN
population     1.5     1.7     3.6     2.4     2.9   200.0  100.0

In [17]:
print(df1.iloc[2:,1]); print("----")
print(df1.iloc[2:,1:]); print("----")
print(df1.loc["Row2":,"year":]); print("----")
print(df1.loc[df1.year >2002,['year','state']]); print("----")
print(df1.loc[df1["year"] >2002,['year','population']]); print("----")
df1.loc[df1.year >2002,"population"]=1000; print(df1)  #assignment

Row3    2002.0
Row4    2001.0
Row5    2002.0
Row6    2003.0
Row7       NaN
Name: year, dtype: float64
----
        year  population
Row3  2002.0         3.6
Row4  2001.0         2.4
Row5  2002.0         2.9
Row6  2003.0       200.0
Row7     NaN       100.0
----
        year  population
Row2  2001.0         1.7
Row3  2002.0         3.6
Row4  2001.0         2.4
Row5  2002.0         2.9
Row6  2003.0       200.0
Row7     NaN       100.0
----
        year   state
Row6  2003.0  Nevada
----
        year  population
Row6  2003.0       200.0
----
       state    year  population
Row1    Ohio  2000.0         1.5
Row2    Ohio  2001.0         1.7
Row3    Ohio  2002.0         3.6
Row4  Nevada  2001.0         2.4
Row5  Nevada  2002.0         2.9
Row6  Nevada  2003.0      1000.0
Row7     NaN     NaN       100.0


In [18]:
#UFUNCS of numpy can used used with Series and Dataframes
print(population_series); print("----")
print(np.mean(population_series))
print(np.std(population_series))
print((population_series - np.mean(population_series))/ np.std(population_series))
print("verified: ",str((1.5-44.58571428571429)/71.83022500653743))  #verify row 1
s2 = pd.Series(list(range(21,28))); print(s2); 
print("----")
print(population_series / s2) #gives NaN as indexes not aligned
print("----")
s2 = pd.Series(list(range(21,28)),index=population_series.index); print(s2) #aligning indexes
print("----")
print(population_series / s2)

Row1      1.5
Row2      1.7
Row3      3.6
Row4      2.4
Row5      2.9
Row6    200.0
Row7    100.0
dtype: float64
----
44.58571428571429
71.83022500653743
Row1   -0.599827
Row2   -0.597043
Row3   -0.570591
Row4   -0.587298
Row5   -0.580337
Row6    2.163634
Row7    0.771462
dtype: float64
verified:  -0.5998270822873374
0    21
1    22
2    23
3    24
4    25
5    26
6    27
dtype: int64
----
Row1   NaN
Row2   NaN
Row3   NaN
Row4   NaN
Row5   NaN
Row6   NaN
Row7   NaN
0      NaN
1      NaN
2      NaN
3      NaN
4      NaN
5      NaN
6      NaN
dtype: float64
----
Row1    21
Row2    22
Row3    23
Row4    24
Row5    25
Row6    26
Row7    27
dtype: int64
----
Row1    0.071429
Row2    0.077273
Row3    0.156522
Row4    0.100000
Row5    0.116000
Row6    7.692308
Row7    3.703704
dtype: float64


In [19]:
df2 = pd.DataFrame(np.array(np.arange(1,51)).reshape(10,5)); print(df2)
df3 = pd.DataFrame(np.array(np.arange(3,53)).reshape(10,5)); print(df3)
df2/df3
df2-df2.loc[0] #operation between a dataframe and a series!!!

    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25
5  26  27  28  29  30
6  31  32  33  34  35
7  36  37  38  39  40
8  41  42  43  44  45
9  46  47  48  49  50
    0   1   2   3   4
0   3   4   5   6   7
1   8   9  10  11  12
2  13  14  15  16  17
3  18  19  20  21  22
4  23  24  25  26  27
5  28  29  30  31  32
6  33  34  35  36  37
7  38  39  40  41  42
8  43  44  45  46  47
9  48  49  50  51  52


0   1   2   3   4
0   0   0   0   0   0
1   5   5   5   5   5
2  10  10  10  10  10
3  15  15  15  15  15
4  20  20  20  20  20
5  25  25  25  25  25
6  30  30  30  30  30
7  35  35  35  35  35
8  40  40  40  40  40
9  45  45  45  45  45

In [20]:
print(df2.loc[:,0])
print(df2-df2.loc[:,0]) #gives wrong result as default operation is row-wise
print("----")
print(df2.subtract(df2.loc[:,0],axis=0)) #operation across columns

0     1
1     6
2    11
3    16
4    21
5    26
6    31
7    36
8    41
9    46
Name: 0, dtype: int32
    0   1   2   3   4   5   6   7   8   9
0   0  -4  -8 -12 -16 NaN NaN NaN NaN NaN
1   5   1  -3  -7 -11 NaN NaN NaN NaN NaN
2  10   6   2  -2  -6 NaN NaN NaN NaN NaN
3  15  11   7   3  -1 NaN NaN NaN NaN NaN
4  20  16  12   8   4 NaN NaN NaN NaN NaN
5  25  21  17  13   9 NaN NaN NaN NaN NaN
6  30  26  22  18  14 NaN NaN NaN NaN NaN
7  35  31  27  23  19 NaN NaN NaN NaN NaN
8  40  36  32  28  24 NaN NaN NaN NaN NaN
9  45  41  37  33  29 NaN NaN NaN NaN NaN
----
   0  1  2  3  4
0  0  1  2  3  4
1  0  1  2  3  4
2  0  1  2  3  4
3  0  1  2  3  4
4  0  1  2  3  4
5  0  1  2  3  4
6  0  1  2  3  4
7  0  1  2  3  4
8  0  1  2  3  4
9  0  1  2  3  4


In [21]:
#aggregation operations
print(s2)
print(s2.mean()) #similarly sum, median, max, min, etc.
print(df2)
print(df2.mean()) #gives column means (that is mean across rows, i.e. by columns, axis = 0 (default))
print(df2.mean(axis=1)) #gives row means (this mean across columns, i.e. by rows, axis = 1)
print(df2.mean(axis='columns')) #same as previous
print(df2.describe())

Row1    21
Row2    22
Row3    23
Row4    24
Row5    25
Row6    26
Row7    27
dtype: int64
24.0
    0   1   2   3   4
0   1   2   3   4   5
1   6   7   8   9  10
2  11  12  13  14  15
3  16  17  18  19  20
4  21  22  23  24  25
5  26  27  28  29  30
6  31  32  33  34  35
7  36  37  38  39  40
8  41  42  43  44  45
9  46  47  48  49  50
0    23.5
1    24.5
2    25.5
3    26.5
4    27.5
dtype: float64
0     3.0
1     8.0
2    13.0
3    18.0
4    23.0
5    28.0
6    33.0
7    38.0
8    43.0
9    48.0
dtype: float64
0     3.0
1     8.0
2    13.0
3    18.0
4    23.0
5    28.0
6    33.0
7    38.0
8    43.0
9    48.0
dtype: float64
               0          1          2          3          4
count  10.000000  10.000000  10.000000  10.000000  10.000000
mean   23.500000  24.500000  25.500000  26.500000  27.500000
std    15.138252  15.138252  15.138252  15.138252  15.138252
min     1.000000   2.000000   3.000000   4.000000   5.000000
25%    12.250000  13.250000  14.250000  15.250000  16.250000
50

In [22]:
#groupby: split-apply-combine
df1 = pd.DataFrame([
("bird", "Falconiformes", 389.0),
("bird", "Psittaciformes", 24.0),
("mammal", "Carnivora", 80.2),
("mammal", "Primates", np.nan),
("mammal", "Carnivora", 58),
],
index=["falcon", "parrot", "lion", "monkey", "leopard"],
columns=("class", "order", "max_speed"),
); df1

class           order  max_speed
falcon     bird   Falconiformes      389.0
parrot     bird  Psittaciformes       24.0
lion     mammal       Carnivora       80.2
monkey   mammal        Primates        NaN
leopard  mammal       Carnivora       58.0

In [23]:
grouped1 = df1.groupby("class"); print(type(grouped1)); print(grouped1.sum()); 
print("----")
grouped2 = df1.groupby("order", axis="columns"); print(grouped2.sum())
print("----")
grouped3 = df1.groupby(["class", "order"]); print(grouped3.sum())
print("----")
print(grouped1.describe())
print("----")
print(grouped1.groups)
print(grouped1.median())

<class 'pandas.core.groupby.generic.DataFrameGroupBy'>
        max_speed
class            
bird        413.0
mammal      138.2
----
Empty DataFrame
Columns: []
Index: []
----
                       max_speed
class  order                    
bird   Falconiformes       389.0
       Psittaciformes       24.0
mammal Carnivora           138.2
       Primates              0.0
----
       max_speed                                                       
           count   mean         std   min     25%    50%     75%    max
class                                                                  
bird         2.0  206.5  258.093975  24.0  115.25  206.5  297.75  389.0
mammal       2.0   69.1   15.697771  58.0   63.55   69.1   74.65   80.2
----
{'bird': ['falcon', 'parrot'], 'mammal': ['lion', 'monkey', 'leopard']}
        max_speed
class            
bird        206.5
mammal       69.1


In [24]:
df2 = pd.DataFrame(
 {
"A": ["foo", "bar", "foo", "bar", "foo", "bar", "foo", "foo"],
"B": ["one", "one", "two", "three", "two", "two", "one", "three"],
"C": np.random.randn(8),
"D": np.random.randn(8),
}
); df2

A      B         C         D
0  foo    one  1.006866 -0.598637
1  bar    one  0.355599 -1.926109
2  foo    two  0.254620 -0.463859
3  bar  three  0.876662  0.705720
4  foo    two  1.589733 -2.848433
5  bar    two  1.298497 -0.451808
6  foo    one -0.532291  0.889263
7  foo  three  0.596753  0.353508

In [25]:
grouped1 = df2.groupby(["A"]); print(grouped1.mean())
print("----")
grouped1 = df2.groupby(["A"]); print(grouped1.count())
print("----")
grouped2 = df2.groupby(["A", "B"]); print(grouped2.mean())

            C         D
A                      
bar  0.843586 -0.557399
foo  0.583136 -0.533632
----
     B  C  D
A           
bar  3  3  3
foo  5  5  5
----
                  C         D
A   B                        
bar one    0.355599 -1.926109
    three  0.876662  0.705720
    two    1.298497 -0.451808
foo one    0.237288  0.145313
    three  0.596753  0.353508
    two    0.922176 -1.656146


In [26]:
df3 = pd.DataFrame(np.random.randint(1,10,25).reshape(5,5));df3
df3.index = ['A','B','C',"D",'E']; df3
df3.columns = ['one','two','three',"four",'five']; print(df3); print(df3.dtypes)
def group_func1(x):
    if x <='C':
        return 'small'
    else:
        return 'large'
grouped1 = df3.groupby(group_func1, axis=0); print(grouped1.mean())
def group_func2(x):
    if x in ['one','two','three']:
        return 'first three col'
    else:
        return 'latter ones'
grouped2 = df3.groupby(group_func2, axis=1); print(grouped2.mean())
print(grouped2.aggregate(np.mean))

   one  two  three  four  five
A    3    6      2     9     3
B    6    6      4     6     2
C    8    4      9     9     7
D    7    5      6     5     2
E    1    1      3     7     3
one      int32
two      int32
three    int32
four     int32
five     int32
dtype: object
            one       two  three  four  five
large  4.000000  3.000000    4.5   6.0   2.5
small  5.666667  5.333333    5.0   8.0   4.0
   first three col  latter ones
A         3.666667          6.0
B         5.333333          4.0
C         7.000000          8.0
D         6.000000          3.5
E         1.666667          5.0
   first three col  latter ones
A         3.666667          6.0
B         5.333333          4.0
C         7.000000          8.0
D         6.000000          3.5
E         1.666667          5.0


In [27]:
#applies to each group a set of aggregation functions across columns
grouped2 = df3.groupby(group_func1)
print(grouped2.aggregate([np.mean,np.median,np.max]))

            one                   two             three             four  \
           mean median amax      mean median amax  mean median amax mean   
large  4.000000    4.0    7  3.000000    3.0    5   4.5    4.5    6  6.0   
small  5.666667    6.0    8  5.333333    6.0    6   5.0    4.0    9  8.0   

                  five              
      median amax mean median amax  
large    6.0    7  2.5    2.5    3  
small    9.0    9  4.0    3.0    7  


In [28]:
#applies to each group a set of aggregation functions across columns (a unique one for each col)
grouped2 = df3.groupby(group_func1)
print(grouped2.aggregate({'one':np.mean,'two': np.median,'three':np.max,'four':np.min,'five':np.std}))

            one  two  three  four      five
large  4.000000  3.0      6     5  0.707107
small  5.666667  6.0      9     6  2.645751


In [29]:
print(df2)
print(df2.groupby(['A']).aggregate(np.std))
#print(df2.groupby(['A']).std())
def filter_func(x):
    return x['C'].std() > 0.5
print(df2.groupby(['A']).filter(filter_func))
print(df2.groupby(['A']).count())
#shape of output of transform same as input 
print(df2.groupby(['A']).transform(lambda x: x/x.count()))

     A      B         C         D
0  foo    one  1.006866 -0.598637
1  bar    one  0.355599 -1.926109
2  foo    two  0.254620 -0.463859
3  bar  three  0.876662  0.705720
4  foo    two  1.589733 -2.848433
5  bar    two  1.298497 -0.451808
6  foo    one -0.532291  0.889263
7  foo  three  0.596753  0.353508
            C         D
A                      
bar  0.472318  1.319088
foo  0.797664  1.429952
     A      B         C         D
0  foo    one  1.006866 -0.598637
2  foo    two  0.254620 -0.463859
4  foo    two  1.589733 -2.848433
6  foo    one -0.532291  0.889263
7  foo  three  0.596753  0.353508
     B  C  D
A           
bar  3  3  3
foo  5  5  5
          C         D
0  0.201373 -0.119727
1  0.118533 -0.642036
2  0.050924 -0.092772
3  0.292221  0.235240
4  0.317947 -0.569687
5  0.432832 -0.150603
6 -0.106458  0.177853
7  0.119351  0.070702


C:\Users\Ujjwa\AppData\Local\Temp/ipykernel_928/2799966967.py:9: FutureWarning: Dropping invalid columns in DataFrameGroupBy.transform is deprecated. In a future version, a TypeError will be raised. Before calling .transform, select only columns which should be valid for the transforming function.
  print(df2.groupby(['A']).transform(lambda x: x/x.count()))


In [30]:
#apply enables application of any  arbitrary function to grouped or ungrouped data
#print(df2)
def my_div(x):
    #print(x)
    print("type: ",type(x))
    return x['C']/x['D']
#when calling apply on grouped objects sub-datframes are passed to x of the function
print(df2.groupby(['A']).apply(my_div))
print("-----")
#when calling apply directly on the dataframe series objects are passed to x of the function
print(df2.apply(my_div,axis=1)) #same as previous

def my_div2(x):
    print("type:: ",type(x))
    if x['C']>0:
        return 100
    else:
        return 0
#when calling apply directly on the dataframe series objects are passed to x of the function
print(df2.apply(my_div2,axis=1))
df2['E']=df2.apply(my_div2,axis=1); print(df2)

def my_div3(x):
    print("type::: ",type(x))
    if x['C']>0 and x['D']>0:
        return True
    else:
        return False
#when calling apply directly on the dataframe, series objects are passed to x of the function
print(df2.apply(my_div3,axis=1))
df2['E']=df2.apply(my_div3,axis=1); print(df2)
print("======================")
#when calling transform use groupby and only series objects are passed to x 
def my_div4(x):
    #print(x)
    return x - x.mean()
print(df2.iloc[:,1:-1].groupby(['B']).transform(my_div4))
        

type:  <class 'pandas.core.frame.DataFrame'>
type:  <class 'pandas.core.frame.DataFrame'>
A     
bar  1   -0.184621
     3    1.242223
     5   -2.874001
foo  0   -1.681930
     2   -0.548916
     4   -0.558108
     6   -0.598575
     7    1.688088
dtype: float64
-----
type:  <class 'pandas.core.series.Series'>
type:  <class 'pandas.core.series.Series'>
type:  <class 'pandas.core.series.Series'>
type:  <class 'pandas.core.series.Series'>
type:  <class 'pandas.core.series.Series'>
type:  <class 'pandas.core.series.Series'>
type:  <class 'pandas.core.series.Series'>
type:  <class 'pandas.core.series.Series'>
0   -1.681930
1   -0.184621
2   -0.548916
3    1.242223
4   -0.558108
5   -2.874001
6   -0.598575
7    1.688088
dtype: float64
type::  <class 'pandas.core.series.Series'>
type::  <class 'pandas.core.series.Series'>
type::  <class 'pandas.core.series.Series'>
type::  <class 'pandas.core.series.Series'>
type::  <class 'pandas.core.series.Series'>
type::  <class 'pandas.core.series.Seri

In [31]:
#created in the most basic way as a dict of lists
d5 = {'state': ['Ohio', 'Ohio', 'Ohio', 'Nevada', 'Nevada', 'Nevada'], 
      'year': [2000, 2001, 2002, 2001, 2002, 2003],
'pop': [1.5, 1.7, 3.6, 2.4, 2.9, 3.2]}
df1 = pd.DataFrame(d5)
df1

state  year  pop
0    Ohio  2000  1.5
1    Ohio  2001  1.7
2    Ohio  2002  3.6
3  Nevada  2001  2.4
4  Nevada  2002  2.9
5  Nevada  2003  3.2

In [32]:
df2 = pd.DataFrame(d5, columns=['pop','state','year','debt'],index=np.arange(2,14,2))
#assign a scalar to a col
df2['debt1'] = 10
df2['debt2'] = [3,8,2,5,9,1]
debt_col = pd.Series([-1.2, -1.5, -1.7], index=[2,10,6])
df2['debt3'] = debt_col
df2['debt4'] = ['a','b','c','d','e','f']
df2['new_col1'] = ['a','b','c','d','e','f']
df2['new_col2'] = df2['pop'] < 2.5
df2['new_col3'] = (df2['pop'] < 2.5) & (df2.state =='Ohio')
df2

pop   state  year debt  debt1  debt2  debt3 debt4 new_col1  new_col2  \
2   1.5    Ohio  2000  NaN     10      3   -1.2     a        a      True   
4   1.7    Ohio  2001  NaN     10      8    NaN     b        b      True   
6   3.6    Ohio  2002  NaN     10      2   -1.7     c        c     False   
8   2.4  Nevada  2001  NaN     10      5    NaN     d        d      True   
10  2.9  Nevada  2002  NaN     10      9   -1.5     e        e     False   
12  3.2  Nevada  2003  NaN     10      1    NaN     f        f     False   

    new_col3  
2       True  
4       True  
6      False  
8      False  
10     False  
12     False

In [33]:
df3 = df2.reindex(list(range(14))); df3

pop   state    year debt  debt1  debt2  debt3 debt4 new_col1 new_col2  \
0   NaN     NaN     NaN  NaN    NaN    NaN    NaN   NaN      NaN      NaN   
1   NaN     NaN     NaN  NaN    NaN    NaN    NaN   NaN      NaN      NaN   
2   1.5    Ohio  2000.0  NaN   10.0    3.0   -1.2     a        a     True   
3   NaN     NaN     NaN  NaN    NaN    NaN    NaN   NaN      NaN      NaN   
4   1.7    Ohio  2001.0  NaN   10.0    8.0    NaN     b        b     True   
5   NaN     NaN     NaN  NaN    NaN    NaN    NaN   NaN      NaN      NaN   
6   3.6    Ohio  2002.0  NaN   10.0    2.0   -1.7     c        c    False   
7   NaN     NaN     NaN  NaN    NaN    NaN    NaN   NaN      NaN      NaN   
8   2.4  Nevada  2001.0  NaN   10.0    5.0    NaN     d        d     True   
9   NaN     NaN     NaN  NaN    NaN    NaN    NaN   NaN      NaN      NaN   
10  2.9  Nevada  2002.0  NaN   10.0    9.0   -1.5     e        e    False   
11  NaN     NaN     NaN  NaN    NaN    NaN    NaN   NaN      NaN      NaN   
12  3.2  Nevada  2003.0  NaN   10.0    1.0    NaN     f        f    False   
13  NaN     NaN     NaN  NaN    NaN    NaN    NaN   NaN      NaN      NaN   

   new_col3  
0       NaN  
1       NaN  
2      True  
3       NaN  
4      True  
5       NaN  
6     False  
7       NaN  
8     False  
9       NaN  
10    False  
11      NaN  
12    False  
13      NaN

In [34]:
# None is a Python object, it cannot be used in any arbitrary NumPy/Pandas array, 
# but only in arrays with data type 'object'
vals1 = np.array([1, 2, 3, 4]); print(vals1); print(vals1.dtype)
vals2 = np.array([1, None, 3, 4]); print(vals2); print(vals2.dtype) # int to object upcast meaning slow native python operation
#1+None #will give error as no operation possible b/w numerical and None

[1 2 3 4]
int32
[1 None 3 4]
object


In [35]:
# NaN is missing value for numerical data, it is a special floating-point value
print(1 + np.NaN)
s1 = pd.Series([1, np.nan, 3, None,5,6]); print(s1)
print(s1.sum()); print(s1.max()); print(s1.min())
print(np.nansum(s1)); print(np.nanmax(s1)); print(np.nanmin(s1)) # to be preferred as more reliable with NaN

nan
0    1.0
1    NaN
2    3.0
3    NaN
4    5.0
5    6.0
dtype: float64
15.0
6.0
1.0
15.0
6.0
1.0


In [36]:
df3.isnull()

pop  state   year  debt  debt1  debt2  debt3  debt4  new_col1  new_col2  \
0    True   True   True  True   True   True   True   True      True      True   
1    True   True   True  True   True   True   True   True      True      True   
2   False  False  False  True  False  False  False  False     False     False   
3    True   True   True  True   True   True   True   True      True      True   
4   False  False  False  True  False  False   True  False     False     False   
5    True   True   True  True   True   True   True   True      True      True   
6   False  False  False  True  False  False  False  False     False     False   
7    True   True   True  True   True   True   True   True      True      True   
8   False  False  False  True  False  False   True  False     False     False   
9    True   True   True  True   True   True   True   True      True      True   
10  False  False  False  True  False  False  False  False     False     False   
11   True   True   True  True   True   True   True   True      True      True   
12  False  False  False  True  False  False   True  False     False     False   
13   True   True   True  True   True   True   True   True      True      True   

    new_col3  
0       True  
1       True  
2      False  
3       True  
4      False  
5       True  
6      False  
7       True  
8      False  
9       True  
10     False  
11      True  
12     False  
13      True

In [37]:
print(df3['pop'])
print(df3['pop'].isnull())
print(df3['pop'].notnull())


0     NaN
1     NaN
2     1.5
3     NaN
4     1.7
5     NaN
6     3.6
7     NaN
8     2.4
9     NaN
10    2.9
11    NaN
12    3.2
13    NaN
Name: pop, dtype: float64
0      True
1      True
2     False
3      True
4     False
5      True
6     False
7      True
8     False
9      True
10    False
11     True
12    False
13     True
Name: pop, dtype: bool
0     False
1     False
2      True
3     False
4      True
5     False
6      True
7     False
8      True
9     False
10     True
11    False
12     True
13    False
Name: pop, dtype: bool


In [38]:
s1 = df3['pop']; print(type(s1))
print(s1);print("----")
print(s1.dropna())
print(s1.dropna().size)

<class 'pandas.core.series.Series'>
0     NaN
1     NaN
2     1.5
3     NaN
4     1.7
5     NaN
6     3.6
7     NaN
8     2.4
9     NaN
10    2.9
11    NaN
12    3.2
13    NaN
Name: pop, dtype: float64
----
2     1.5
4     1.7
6     3.6
8     2.4
10    2.9
12    3.2
Name: pop, dtype: float64
6


In [39]:
#By default, dropna() will drop all rows in which any null value is present
print(df3.dropna()); print("---")
print(df3.dropna(axis=1)); print("---") #drops all cols having even a single null value
print(df2)
print(df2.dropna(axis=1)) #debt,debt3 have been dropped


Empty DataFrame
Columns: [pop, state, year, debt, debt1, debt2, debt3, debt4, new_col1, new_col2, new_col3]
Index: []
---
Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13]
---
    pop   state  year debt  debt1  debt2  debt3 debt4 new_col1  new_col2  \
2   1.5    Ohio  2000  NaN     10      3   -1.2     a        a      True   
4   1.7    Ohio  2001  NaN     10      8    NaN     b        b      True   
6   3.6    Ohio  2002  NaN     10      2   -1.7     c        c     False   
8   2.4  Nevada  2001  NaN     10      5    NaN     d        d      True   
10  2.9  Nevada  2002  NaN     10      9   -1.5     e        e     False   
12  3.2  Nevada  2003  NaN     10      1    NaN     f        f     False   

    new_col3  
2       True  
4       True  
6      False  
8      False  
10     False  
12     False  
    pop   state  year  debt1  debt2 debt4 new_col1  new_col2  new_col3
2   1.5    Ohio  2000     10      3     a        a      True      True
4   1.7    O

In [40]:
print(df2)
print(df2.dropna(axis='columns',thresh=3)) #debt dropped but debt3 remains - thresh=min. no. of not nulls in col/row

    pop   state  year debt  debt1  debt2  debt3 debt4 new_col1  new_col2  \
2   1.5    Ohio  2000  NaN     10      3   -1.2     a        a      True   
4   1.7    Ohio  2001  NaN     10      8    NaN     b        b      True   
6   3.6    Ohio  2002  NaN     10      2   -1.7     c        c     False   
8   2.4  Nevada  2001  NaN     10      5    NaN     d        d      True   
10  2.9  Nevada  2002  NaN     10      9   -1.5     e        e     False   
12  3.2  Nevada  2003  NaN     10      1    NaN     f        f     False   

    new_col3  
2       True  
4       True  
6      False  
8      False  
10     False  
12     False  
    pop   state  year  debt1  debt2  debt3 debt4 new_col1  new_col2  new_col3
2   1.5    Ohio  2000     10      3   -1.2     a        a      True      True
4   1.7    Ohio  2001     10      8    NaN     b        b      True      True
6   3.6    Ohio  2002     10      2   -1.7     c        c     False     False
8   2.4  Nevada  2001     10      5    NaN     d  

In [41]:
print(df2)
print(df2.fillna(axis='columns',method='ffill'))
print(df2.fillna(axis=1,method='ffill')) #borrows values along rows i.e. across cols
print(df2.fillna(axis=1,method='bfill')) #borrows values along rows i.e. across cols
print(df2.fillna(axis=1,method='bfill').dtypes); print("------") #notice the dtypes of all cols have become "object"
print(df2.fillna(axis=0,method='bfill')) #borrows values along column i.e. across rows
print(df2.fillna(axis=0,method='bfill').dtypes)
print(df2.fillna(axis=0,method='bfill')) 

    pop   state  year debt  debt1  debt2  debt3 debt4 new_col1  new_col2  \
2   1.5    Ohio  2000  NaN     10      3   -1.2     a        a      True   
4   1.7    Ohio  2001  NaN     10      8    NaN     b        b      True   
6   3.6    Ohio  2002  NaN     10      2   -1.7     c        c     False   
8   2.4  Nevada  2001  NaN     10      5    NaN     d        d      True   
10  2.9  Nevada  2002  NaN     10      9   -1.5     e        e     False   
12  3.2  Nevada  2003  NaN     10      1    NaN     f        f     False   

    new_col3  
2       True  
4       True  
6      False  
8      False  
10     False  
12     False  
    pop   state  year  debt debt1 debt2 debt3 debt4 new_col1 new_col2 new_col3
2   1.5    Ohio  2000  2000    10     3  -1.2     a        a     True     True
4   1.7    Ohio  2001  2001    10     8     8     b        b     True     True
6   3.6    Ohio  2002  2002    10     2  -1.7     c        c    False    False
8   2.4  Nevada  2001  2001    10     5     5 

In [42]:
import seaborn as sns
titanic = sns.load_dataset('titanic')

In [43]:
titanic.head()

survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True

In [44]:
titanic.groupby(['sex', 'class'])['survived'].aggregate('mean')

sex     class 
female  First     0.968085
        Second    0.921053
        Third     0.500000
male    First     0.368852
        Second    0.157407
        Third     0.135447
Name: survived, dtype: float64

In [45]:
#converts from hierarchical index to a more visually appealing layout - PIVOT Table
titanic.groupby(['sex', 'class'])['survived'].aggregate('mean').unstack()

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [46]:
#direct PIVOT table feature available in pandas
titanic.pivot_table('survived', index='sex', columns='class')

class      First    Second     Third
sex                                 
female  0.968085  0.921053  0.500000
male    0.368852  0.157407  0.135447

In [47]:
age = pd.cut(titanic['age'], [0, 18, 80])
titanic.pivot_table('survived', ['sex', age], 'class')

class               First    Second     Third
sex    age                                   
female (0, 18]   0.909091  1.000000  0.511628
       (18, 80]  0.972973  0.900000  0.423729
male   (0, 18]   0.800000  0.600000  0.215686
       (18, 80]  0.375000  0.071429  0.133663

In [48]:
fare = pd.qcut(titanic['fare'], 2)
titanic.pivot_table('survived', ['sex', age], [fare, 'class'])

fare            (-0.001, 14.454]                     (14.454, 512.329]  \
class                      First    Second     Third             First   
sex    age                                                               
female (0, 18]               NaN  1.000000  0.714286          0.909091   
       (18, 80]              NaN  0.880000  0.444444          0.972973   
male   (0, 18]               NaN  0.000000  0.260870          0.800000   
       (18, 80]              0.0  0.098039  0.125000          0.391304   

fare                                 
class              Second     Third  
sex    age                           
female (0, 18]   1.000000  0.318182  
       (18, 80]  0.914286  0.391304  
male   (0, 18]   0.818182  0.178571  
       (18, 80]  0.030303  0.192308

In [49]:
#vectorized string operation - through the str attribute of pandas Series and Index objects
data = ['rajeev', 'pradeep', 'jagdeep', 'trideep','jagandeep']; 
print([s.capitalize() for s in data]) #list comprehension syntax which does not work with missing values
data = ['rajeev', 'pradeep', None, 'jagdeep', 'trideep', 'jagandeep']
#[s.capitalize() for s in data] #will give error - 'NoneType' object has no attribute 'capitalize'
names = pd.Series(data)
print(names.str.capitalize())
print(names.str.contains('ee'))
print(names.str.split('ee')) #many other methods of the str attrib.-len,lower,islower,isdigit,lstrip,endswith,find, etc.
print(names.str.join('::'))
print(names.str[2:4])

['Rajeev', 'Pradeep', 'Jagdeep', 'Trideep', 'Jagandeep']
0       Rajeev
1      Pradeep
2         None
3      Jagdeep
4      Trideep
5    Jagandeep
dtype: object
0    True
1    True
2    None
3    True
4    True
5    True
dtype: object
0       [raj, v]
1      [prad, p]
2           None
3      [jagd, p]
4      [trid, p]
5    [jagand, p]
dtype: object
0             r::a::j::e::e::v
1          p::r::a::d::e::e::p
2                         None
3          j::a::g::d::e::e::p
4          t::r::i::d::e::e::p
5    j::a::g::a::n::d::e::e::p
dtype: object
0      je
1      ad
2    None
3      gd
4      id
5      ga
dtype: object


In [50]:
peculiar = pd.DataFrame({'name': names,'info': ['B|C|D', 'B|D', 'A|C', 'B|D', 'B|C', 'B|C|D']}); peculiar

name   info
0     rajeev  B|C|D
1    pradeep    B|D
2       None    A|C
3    jagdeep    B|D
4    trideep    B|C
5  jagandeep  B|C|D

In [51]:
peculiar['info'].str.get_dummies("|")

A  B  C  D
0  0  1  1  1
1  0  1  0  1
2  1  0  1  0
3  0  1  0  1
4  0  1  1  0
5  0  1  1  1

In [52]:
df29 = pd.read_csv('ex2.csv', names=['a', 'b', 'c', 'd', 'message'], index_col='message')
df29

FileNotFoundError: [Errno 2] No such file or directory: 'ex2.csv'

In [ ]:
df31 = pd.read_table('ex4.txt', sep='\s+')
df31