In [1]:
import numpy as np
import matplotlib.pyplot as plt
import jax
from jax import jacfwd, jacrev

### Question 1

In [2]:
def f1(x):
   
    return (x[1]-x[0]**2)**2 + (np.exp(x[0]**2))

In [3]:
f1((1,2))

3.718281828459045

In [4]:
2/(1+np.sqrt(5))

0.6180339887498948

In [5]:
def Golden_Section(f,x1,x2,e=0.2):
    x1=np.array(x1)
    x2=np.array(x2)
    gr=(1+np.sqrt(5))/2
    a=x1+(x2-x1)/gr
    b=x2-(x2-x1)/gr
    l=[(a+b)/2]
    length=[np.linalg.norm(x1-x2)]
    intera=[x1]
    interb=[x2]
    
    
#     length=[np.linalg.norm(a-b)]
#     intera=[a]
#     interb=[b]
    while np.linalg.norm(a-b)>e:
        if f(a)>f(b):
            x2=a
        else:
            x1=b
            
        length.append(np.linalg.norm(a-b))
        intera.append(a)
        interb.append(b)
        a=x1+(x2-x1)/gr
        b=x2-(x2-x1)/gr
        l.append((a+b)/2)
        
    return l,length,intera,interb

In [6]:
L,Length,A,B=Golden_Section(f1,(0,1),(1,2))

In [7]:
L

[array([0.5, 1.5]),
 array([0.30901699, 1.30901699]),
 array([0.19098301, 1.19098301])]

In [8]:
#The Step Lengths

Length

[1.4142135623730951, 0.33385053542218923, 0.20633097805326353]

In [9]:
#X1

A

[array([0, 1]),
 array([0.61803399, 1.61803399]),
 array([0.38196601, 1.38196601])]

In [10]:
#X2

B

[array([1, 2]),
 array([0.38196601, 1.38196601]),
 array([0.23606798, 1.23606798])]

In [11]:
#Functioanl Values of X1

[f1(a) for a in A]

[2.0, 2.993026330252599, 2.684942244111319]

In [12]:
#Functional Values of X2

[f1(b) for b in B]

[3.718281828459045, 2.684942244111319, 2.450512401465571]